Improved huggingface batch logic
SeldonIO/MLServer pull request #1336
Opened 2023-08-15 19:25 UTC by ajsalow

Addresses issues described in https://github.com/SeldonIO/MLServer/issues/1249 where batch size greater than 0 causes some hugging face models to fail loading.

2023-08-24 10:19 UTC, adriangonz requested changes
Changes look good! Thanks for taking the time to contribute this patch @ajsalow. 

Before merging, could you add a test covering the new behaviour? Besides that, there also seem to be some conflicts with latest `master`.

2023-08-27 22:21 UTC, ajsalow commented
Thanks for taking a look @adriangonz. I've added some test coverage, let me know if anything else is needed.

2023-08-30 13:14 UTC, adriangonz approved these changes
Looks good! Thanks for adding that test @ajsalow :+1:

2023-08-31 09:23 UTC, adriangonz commented
Hey @ajsalow ,

Just had a look at the test failures. I think from those, the `lint` failure is probably the key one - everything else seems to be just flaky. So once you get a chance to address the linter error, we should be good to merge this one:

```
./runtimes/huggingface/mlserver_huggingface/common.py:72:89: E501 line too long (120 > 88 characters)
```

2023-09-05 15:58 UTC, merged