added model_kwargs to huggingface model
SeldonIO/MLServer pull request #1417
Opened 2023-09-27 18:16 UTC by nanbo-liu

This is for issue [1344](https://github.com/SeldonIO/MLServer/issues/1344)
This allow `model-setting.json` to take `model_kwargs`:
example below:
```json
{
    "name": "llama",
    "implementation": "mlserver_huggingface.HuggingFaceRuntime",
    "parameters": {
        "extra": {
            "task": "text-generation",
            "pretrained_model": "daryl149/llama-2-7b-hf",
            "model_kwargs": {
                "device_map": "auto",
                "load_in_8bit": true
            }
        }
    }
}

```

2023-10-03 13:38 UTC, adriangonz requested changes
Nice one @nanbo-liu! This would be a great addition to the HF runtime - thanks for contributing it :rocket: 

Changes look good - although, could you add some tests to validate that the model kwargs get used? Once tests are in, we should be good to land this one. :+1:

2023-10-03 17:23 UTC, nanbo-liu commented
@adriangonz ,added unit tests from the latest commit.

2023-10-04 08:30 UTC, adriangonz approved these changes
Brilliant! Thanks for the changes @nanbo-liu ! 

This should be good to go now :rocket:

2023-10-04 15:30 UTC, nanbo-liu commented
@adriangonz ,I rewrite the unit test a little bit. The previous version depends on package `accelerate`.
I don't want to introduce extra dependency into this repo. Would you take an another look when you have a chance.
Need to rerun workflow

2023-10-05 15:21 UTC, nanbo-liu commented
@adriangonz, just fixed the unit test bug. would you try again

2023-10-10 14:52 UTC, nanbo-liu commented
@adriangonz ,CICD keeps getting runtime error for `catboost`

2023-10-18 16:04 UTC, adriangonz commented
Yuuup, it seems there's an unrelated error in the `catboost` runtime causing some actions to fail. Which means this PR should be good to go as-is :+1:

2023-10-18 16:04 UTC, merged