Update mlserver_huggingface settings device type
SeldonIO/MLServer pull request #1486
Opened 2023-11-15 19:26 UTC by geodavic

If using a `model-settings.json` of the following form:
```json
{
    "name": "my-model",
    "implementation": "mlserver_huggingface.HuggingFaceRuntime",
    "parameters": {
        "extra": {
            "task": "text-generation",
            "pretrained_model": "model/path",
            "model_kwargs": {
                "load_in_8bit": true
            }
        }
    }
}
```

an error occurs when spinning up the server:
```
The model has been loaded with `accelerate` and therefore cannot be moved to a specific device. Please discard the `device` argument when creating your pipeline object.
```
because the `load_in_8bit` model kwarg makes forces the model to be loaded with Accelerate, and `HuggingFaceSettings.device` default value of -1 is passed. I tried simply passing `"device": null` to the model settings json, but this wasn't accepted because the schema is typed to `int`.

The solution is to expand the typing of `HuggingFaceSettings.device` to accept null. Therefore I have updated the typing to `Optional[Union[int,str]]`, which is very close to the type hint used in the transformers [pipeline](https://github.com/huggingface/transformers/blob/main/src/transformers/pipelines/__init__.py#L542).

I have tested that `"device": null` now works in `model-settings.json` and the server starts as expected.

2023-11-15 19:34 UTC, nanbo-liu commented
@adriangonz

2023-11-23 14:20 UTC, adriangonz requested changes
Looks great @geodavic! :rocket:  

Would it make sense adding a small test to make sure this behaviour doesn't change in the future? This could be as simple as loading a model with `device` set to empty, `-1`, or `cpu`? And just asserting that the model loads correctly.

2023-11-27 17:50 UTC, geodavic commented
@adriangonz Thanks! I added a test that passes `None`, `-1` and `cpu` for the device to ensure they all load into cpu.

2023-12-18 15:35 UTC, geodavic commented
@sakoush if you don't mind taking a look, much appreciated!

2024-01-16 17:43 UTC, jyono commented
@adriangonz @sakoush 

is there anything holding this back?

2024-03-11 22:47 UTC, sakoush approved these changes
Lgtm. Many thanks for your contribution.

2024-03-11 22:48 UTC, merged