#1926 added dependency upgrades for python3.12 support
SeldonIO/MLServer pull request #1951
Opened 2024-11-09 04:56 UTC by shivakrishnaah

2024-11-09 04:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SeldonIO/MLServer?pullRequest=1951) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SeldonIO/MLServer?pullRequest=1951) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SeldonIO/MLServer?pullRequest=1951) it.</sub>

2024-11-09 05:02 UTC, shivakrishnaah commented
# Pull Request
fixes #1926 

## Description
Upgraded most of the dependencies to support python3.12 version

## Changes Made
Upgraded the dependencies and the python docker images

## Checklist
<!-- Make sure to check the items below before submitting your pull request -->

- [X ] Code follows the project's style guidelines
- [ ] All tests related to the changes pass successfully
- [ ] Documentation is updated (if necessary)
- [ ] Code is reviewed by at least one other team member
- [ ] Any breaking changes are communicated and documented

2024-11-11 09:49 UTC, sakoush requested changes
@shivakrishnaah many thanks for your great contribution to add support for python 3.12.

To keep the changes for this PR as minimal as possible, lets _just_ add support for python 3.12 and keep the default version of mlserver at python 3.10 for now. We cannot upgrade everything to python 3.12 at the moment as this will break other workflows that we have.

So lets revert the changes to the CI / dockerfile.

I have triggered the CI anyway so that we can look at the tests status.

2024-11-11 09:49 UTC, sakoush commented on .github/workflows/tests.yml
> +          - "3.12"
add 3.11

2024-11-11 09:49 UTC, sakoush commented on .github/workflows/benchmark.yml
> -      - name: Set up Python 3.10
lets keep the CI at python `3.10` as it is related to the main docker python version, and just add support for 3.11 and 3.12 if thats possible.

2024-11-11 09:49 UTC, sakoush commented on .github/workflows/benchmark.yml
> -          python-version: "3.10"
ditto

2024-11-11 09:49 UTC, sakoush commented on .github/workflows/licenses.yml
> -      - name: Set up Python 3.10
ditto

2024-11-11 09:49 UTC, sakoush commented on .github/workflows/licenses.yml
> -          python-version: "3.10"
ditto

2024-11-11 09:49 UTC, sakoush commented on .github/workflows/release.yml
> -      - name: Set up Python 3.10
ditto

2024-11-11 09:49 UTC, sakoush commented on .github/workflows/release.yml
> -          python-version: "3.10"
ditto

2024-11-11 09:49 UTC, sakoush commented on .github/workflows/release.yml
> -      - name: Set up Python 3.10
ditto

2024-11-11 09:49 UTC, sakoush commented on .github/workflows/release.yml
> -          python-version: "3.10"
ditto

2024-11-11 09:49 UTC, sakoush commented on .github/workflows/tests.yml
> +          - "3.12"
add 3.11

2024-11-11 09:49 UTC, sakoush commented on .github/workflows/tests.yml
> +          - "3.12"
add 3.11

2024-11-11 09:49 UTC, sakoush commented on .readthedocs.yaml
> -    python: "3.10"
ditto

2024-11-11 09:49 UTC, sakoush commented on Dockerfile
> -FROM python:3.10-slim AS wheel-builder
lets leave the default mlserver docker image that we build as part of the CI at python 3.10, if we want a docker image for different python version then the options are:
- parameterise this `Dockerfile` to take the python version as argument.
- provide instructions on how to build a docker image with a different python version

In any case I think this should be done as a follow up PR perhaps.

2024-11-11 09:49 UTC, sakoush commented on docs-gb/examples/conda/environment.yml
> -    - python == 3.8
these are part of examples, perhaps leave them as they are?

2024-11-11 09:49 UTC, sakoush commented on docs/conf.py
> -        "repo_url": "https://github.com/SeldonIO/MLServer/",
revert

2024-11-11 09:49 UTC, sakoush commented on docs/examples/conda/environment.yml
> -    - python == 3.8
ditto

2024-11-11 09:49 UTC, sakoush commented on mlserver/cli/constants.py
> +    conda install gxx_linux-aarch64 && source activate
why are these required?

2024-11-11 09:49 UTC, sakoush commented on poetry.lock
> +# This file is automatically @generated by Poetry 1.8.4 and should not be changed by hand.
is there a reason why the lock file has to change almost completely? There are internal libraries that have been downgraded (e.g. `alibi` and `alibi-detect`) that at least should be reverted.

2024-11-11 09:49 UTC, sakoush commented on pyproject.toml
> +pydantic = "*"
is this redundant as above `pydantic` rule is defined?

2024-11-11 09:49 UTC, sakoush commented on pyproject.toml
> +tensorflow = ">=2.16"
why are these required?

2024-11-11 09:49 UTC, sakoush commented on runtimes/alibi-detect/pyproject.toml
> +tensorflow = ">=2.16"
why are these required?

2024-11-11 09:49 UTC, sakoush commented on runtimes/alibi-detect/pyproject.toml
> +tensorflow = ">=2.16"
why are these required?

2024-11-11 09:49 UTC, sakoush commented on runtimes/alibi-explain/pyproject.toml
> +alibi = "0.9.6"
why is this required? this is an old version.

2024-11-11 09:49 UTC, sakoush commented on runtimes/alibi-explain/pyproject.toml
> +tensorflow = ">=2.16"
ditto

2024-11-11 09:49 UTC, sakoush commented on tests/test_env.py
> +    ["python3.9", "python3.11", "python3.12"],
keep the extra empty python version `""`

2024-11-11 09:49 UTC, sakoush commented on tests/testdata/environment.yml
> +  - python == 3.12
ditto

2024-11-11 09:49 UTC, sakoush commented on tox.ini
> +    GITHUB_REPOSITORY = {env:GITHUB_REPOSITORY:shivakrishnaah/MLServer}
revert

2024-11-11 09:49 UTC, sakoush commented on tox.ini
> +    GITHUB_REPOSITORY = {env:GITHUB_REPOSITORY:shivakrishnaah/MLServer}
revert

2024-11-18 14:42 UTC, sakoush commented
@shivakrishnaah Many thanks for your recent changes. There are some issues with the CI (check [here](https://github.com/SeldonIO/MLServer/actions/runs/11862265518/job/33081687689?pr=1951) as an example):

`pyproject.toml changed significantly since poetry.lock was last generated. Run `poetry lock [--no-update]` to fix the lock file.`


The first thing that needs to be fixed perhaps on your PR is to run `make lock` at the top level to refresh poetry lock files for mlserver.

There are a few things to note on top:
- Torch min version required for py 3.12 support is py 2.4, check [here](https://github.com/pytorch/pytorch/releases/tag/v2.4.0). This needs to be updated.
- Some tests are fail in my local env. They will need to be addressed.
- Some internal libraries (e.g. `alibi` and `alibi-detect` pin their TF dependencies to be <2.15 and therefore we will also have to upgrade these internal libraries before accepting this change (we will upgrade these libraries ourselves). Perhaps then do not look at changes / tests for these runtimes for now: `mlserver-alibi-detect` and `mlserver-alibi-explain`.

note: I could not push to your fork so I created this [branch](https://github.com/sakoush/MLServer/commits/quickfix/py3.12/) as a reference to you. Feel free to use the commits on top of your changes as reference.

2024-11-18 15:48 UTC, sakoush commented
@shivakrishnaah please have a look at the CI as there are numerous tests failing and they will need to be resolved as part of your change (exclude as discussed for now `alibi-explain` and `alibi-detect` tests). Please let me know if you have any questions.

2024-12-17 15:26 UTC, sakoush approved these changes
LGTM. Thanks for the initial work @shivakrishnaah I have done some extra work to get it over the line in the last few days. 

Some of the CI tasks still fail which I will investigate before merging.

2024-12-17 16:34 UTC, sakoush commented
failing tests are all isolated in `test_lib_path`, we will look into it in a follow up PR.

2024-12-17 16:58 UTC, merged